export const IMAGES = {
  logo: '/images/logo.png',
  glassBottle: '/images/glass-bottle.png',
  eyeIcon: '/images/eye.png',
  googleIcon: '/images/google.png',
  ajust: '/images/ajust.png',
  bib: '/images/bib.png',
  chart: '/images/chart.png',
  circle: '/images/circle.png',
  coins: '/images/coins.png',
  home: '/images/home.png',
  signout: '/images/signout.png',
  star: '/images/star.png',
  hist: '/images/hist.png',
  user: '/images/users.png',
  vineoil:'/images/VINEO_IL.png',
  bottle:'/images/bottle.png',
  answer:'/images/answer.png',
  winebox:'/images/bottlebox.png',
  boxgif:'/images/boxgif.gif',
  graph:'/images/graph.gif',
  bottleimg:'/images/bottleimage 1.png',
  bottleglass:'/images/bottle&glass.png',
  letter: '/images/letter.png',
  gif2: '/images/gif2.gif',
  watsap: '/images/watsapp.png',
  facebk: '/images/facebk.png',
  insta: '/images/insta.png',

};
